export { default as Home } from "./Home/Home"
export { default as Experience } from "./Experience/Experience"
export { default as Projects } from "./Projects/Projects"
export { default as Education } from "./Education/Education"
export { default as About } from "./AboutMe/AboutMe"